
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mubsi
 */
public class AddButton extends javax.swing.JFrame {

    /**
     * Creates new form AddButton
     */
    public AddButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelAdd_Entries = new javax.swing.JPanel();
        lblCarBrand = new javax.swing.JLabel();
        txtCarBrand = new javax.swing.JTextField();
        lblFuelType = new javax.swing.JLabel();
        lblGearType = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblCarName = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtCarName = new javax.swing.JTextField();
        lblBaslik = new javax.swing.JLabel();
        jComboboxFuelType = new javax.swing.JComboBox<>();
        jComboBoxGearType = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        lblMyImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 475));
        setPreferredSize(new java.awt.Dimension(810, 485));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelAdd_Entries.setBackground(new java.awt.Color(0, 0, 0,80) );

        lblCarBrand.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        lblCarBrand.setForeground(new java.awt.Color(255, 255, 255));
        lblCarBrand.setText("Car Brand");

        lblFuelType.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        lblFuelType.setForeground(new java.awt.Color(255, 255, 255));
        lblFuelType.setText("Fuel Type");

        lblGearType.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        lblGearType.setForeground(new java.awt.Color(255, 255, 255));
        lblGearType.setText("Gear Type");

        lblPrice.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice.setText("Price");

        lblCarName.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        lblCarName.setForeground(new java.awt.Color(255, 255, 255));
        lblCarName.setText("Car Name");

        lblBaslik.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        lblBaslik.setForeground(new java.awt.Color(255, 255, 255));
        lblBaslik.setText("ENTRY YOUR CAR TO THE LIST");

        jComboboxFuelType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboboxFuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Gasoline", "Diesel", "Hybrid", "LPG" }));

        jComboBoxGearType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBoxGearType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Automatic", "Manuel" }));

        javax.swing.GroupLayout jpanelAdd_EntriesLayout = new javax.swing.GroupLayout(jpanelAdd_Entries);
        jpanelAdd_Entries.setLayout(jpanelAdd_EntriesLayout);
        jpanelAdd_EntriesLayout.setHorizontalGroup(
            jpanelAdd_EntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelAdd_EntriesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpanelAdd_EntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelAdd_EntriesLayout.createSequentialGroup()
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelAdd_EntriesLayout.createSequentialGroup()
                        .addGroup(jpanelAdd_EntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFuelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarName, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(lblGearType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelAdd_EntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCarName, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(txtCarBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(jComboboxFuelType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxGearType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblBaslik, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpanelAdd_EntriesLayout.setVerticalGroup(
            jpanelAdd_EntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelAdd_EntriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBaslik, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelAdd_EntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jpanelAdd_EntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jpanelAdd_EntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboboxFuelType)
                    .addComponent(lblFuelType, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jpanelAdd_EntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGearType, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jComboBoxGearType))
                .addGap(18, 18, 18)
                .addGroup(jpanelAdd_EntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jpanelAdd_Entries, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 440));

        btnSubmit.setBackground(new java.awt.Color(102, 255, 102));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 140, 50));

        lblMyImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashScreen/Assets/lockImagem.jpg"))); // NOI18N
        getContentPane().add(lblMyImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void closeFirstScreen(){
        WindowEvent windowsClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowsClosingEvent);
    
    }
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        
        try {
            String carBrand,carName,price_1;
            carBrand=txtCarBrand.getText();
            carName =txtCarName.getText();          
            var fuelType =jComboboxFuelType.getSelectedItem();
            var gearType = jComboBoxGearType.getSelectedItem();
            price_1 = txtPrice.getText();
            float price = Float.parseFloat(price_1);
            
            String query = "EXEC [dbo].[sp_AddToDatabase] '"+carBrand+"','"+carName+"','"+fuelType+"','"+gearType+"','"+price+"'";           
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            String connectionUrl = "jdbc:sqlserver://MBS;databaseName=searchapplication;integratedSecurity=true;trustServerCertificate=true;"; 
            Connection connection = DriverManager.getConnection(connectionUrl);
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(query);
        }
            

        
        
        catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        int input = JOptionPane.showConfirmDialog(null, "Do you want to stay in the page ?","Select an option",JOptionPane.YES_NO_OPTION);
        try{
        if(input == 1){
            Thread.sleep(100);
            SearchApplication searchApplication = new SearchApplication();
            searchApplication.setVisible(true);
            setVisible(false);
        }
        }
        catch(Exception e){
                System.out.println(e);
                }
        
        
    }//GEN-LAST:event_btnSubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> jComboBoxGearType;
    private javax.swing.JComboBox<String> jComboboxFuelType;
    private javax.swing.JPanel jpanelAdd_Entries;
    private javax.swing.JLabel lblBaslik;
    private javax.swing.JLabel lblCarBrand;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblFuelType;
    private javax.swing.JLabel lblGearType;
    private javax.swing.JLabel lblMyImage;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JTextField txtCarBrand;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
