
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mubsi
 */
public class MyScreen extends javax.swing.JFrame {

    /**
     * Creates new form MyScreen
     */
    public MyScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackgroundColour = new javax.swing.JPanel();
        lblArabaImage = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        lblInformation = new javax.swing.JLabel();
        lblMarkaAdi = new javax.swing.JLabel();
        lblLoadingValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlBackgroundColour.setBackground(new java.awt.Color(0, 0, 51));
        pnlBackgroundColour.setPreferredSize(new java.awt.Dimension(900, 400));
        pnlBackgroundColour.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblArabaImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashScreen/Assets/Arabam.jpg"))); // NOI18N
        lblArabaImage.setText("jLabel1");
        pnlBackgroundColour.add(lblArabaImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 350));
        pnlBackgroundColour.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 900, 20));

        lblInformation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInformation.setForeground(new java.awt.Color(204, 0, 0));
        lblInformation.setText("Loading...");
        pnlBackgroundColour.add(lblInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 356, 250, 20));

        lblMarkaAdi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMarkaAdi.setForeground(new java.awt.Color(255, 255, 255));
        lblMarkaAdi.setText("ARABA ARAMA MOTORUM");
        pnlBackgroundColour.add(lblMarkaAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 330, 30));

        lblLoadingValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLoadingValue.setForeground(new java.awt.Color(204, 0, 0));
        lblLoadingValue.setText("0%");
        pnlBackgroundColour.add(lblLoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackgroundColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackgroundColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
           MyScreen myScreen = new MyScreen(); 
           myScreen.setVisible(true);
        
         try { 
            for(int i =0 ; i<= 100 ; i++){
                Thread.sleep(40);
                myScreen.lblLoadingValue.setText(i +"%");
                
                if(i== 10){
                    myScreen.lblInformation.setText("Turning Modules...");                   
                }
                if(i== 30){
                    myScreen.lblInformation.setText("Loading Modules...");                   
                }
                if(i== 50){
                    myScreen.lblInformation.setText("Connection to Database...");                   
                }
                if(i== 70){
                    myScreen.lblInformation.setText("Connection Successful...");                   
                }
                if(i== 90){
                    myScreen.lblInformation.setText("Launching...");                   
                }
                myScreen.LoadingBar.setValue(i);
            } 
            myScreen.setVisible(false);
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar LoadingBar;
    public javax.swing.JLabel lblArabaImage;
    public javax.swing.JLabel lblInformation;
    public javax.swing.JLabel lblLoadingValue;
    public javax.swing.JLabel lblMarkaAdi;
    private javax.swing.JPanel pnlBackgroundColour;
    // End of variables declaration//GEN-END:variables
}
