
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.io.Serializable;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.put;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mubsi
 */
public class SearchApplication extends javax.swing.JFrame implements Serializable{
    
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form SearchApplication
     */
    public SearchApplication() {
        initComponents();
        setVisible(true);
        
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrice = new javax.swing.JLabel();
        lblTypeOfFuel = new javax.swing.JLabel();
        txtMinPrice = new javax.swing.JTextField();
        txtMaxPrice = new javax.swing.JTextField();
        lblTypeOfGear = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCars = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        comboboxFuelType = new javax.swing.JComboBox<>();
        comboboxGearType = new javax.swing.JComboBox<>();
        btnHelp = new javax.swing.JButton();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Search Application");
        setMinimumSize(new java.awt.Dimension(900, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setText("Price");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 87, -1));

        lblTypeOfFuel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTypeOfFuel.setText("Type of Fuel");
        getContentPane().add(lblTypeOfFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 94, -1));

        txtMinPrice.setText("Min");
        txtMinPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMinPriceMouseClicked(evt);
            }
        });
        txtMinPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtMinPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 80, 30));

        txtMaxPrice.setText("Max");
        txtMaxPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaxPriceMouseClicked(evt);
            }
        });
        txtMaxPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaxPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 80, 30));

        lblTypeOfGear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTypeOfGear.setText("Type Of Gear");
        getContentPane().add(lblTypeOfGear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 99, -1));

        btnSearch.setBackground(new java.awt.Color(204, 204, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(102, 102, 255)));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 143, 57));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jTableCars.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTableCars.setForeground(new java.awt.Color(0, 0, 153));
        jTableCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Brand", "Car Name", "Type Of Fuel", "Type Of Gear", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableCars.setRowHeight(25);
        jScrollPane1.setViewportView(jTableCars);
        if (jTableCars.getColumnModel().getColumnCount() > 0) {
            jTableCars.getColumnModel().getColumn(0).setResizable(false);
            jTableCars.getColumnModel().getColumn(1).setResizable(false);
            jTableCars.getColumnModel().getColumn(2).setResizable(false);
            jTableCars.getColumnModel().getColumn(3).setResizable(false);
            jTableCars.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 870, 280));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 107, 44));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 105, 44));

        comboboxFuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Gasoline", "Diesel", "Hybrid", "LPG" }));
        comboboxFuelType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxFuelTypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxFuelType, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 94, -1));

        comboboxGearType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Manual", "Automatic" }));
        comboboxGearType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxGearTypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxGearType, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 99, -1));

        btnHelp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, 20));

        lblBrand.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBrand.setText("Brand");
        getContentPane().add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, 79, -1));

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });
        getContentPane().add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 30));

        lblModel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblModel.setText("Model");
        getContentPane().add(lblModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, 20));

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });
        getContentPane().add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 120, 30));

        jPanel.setBackground(new java.awt.Color(255, 204, 204));
        jPanel.setPreferredSize(new java.awt.Dimension(900, 450));
        getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void closeFirstScreen(){
        WindowEvent windowsClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowsClosingEvent);
    
    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableCars.getModel();

        model.setRowCount(0);
        try {
            
            String carBrand,carName,minPrice_1,maxPrice_2;
            carBrand=txtBrand.getText();
            carName =txtModel.getText();
            minPrice_1 =txtMinPrice.getText();
            maxPrice_2=txtMaxPrice.getText();
            var typeOfFuel =comboboxFuelType.getSelectedItem().toString();
            var typeOfGear = comboboxGearType.getSelectedItem().toString();
            
            if (typeOfFuel.equals(" ")){ typeOfFuel="";}
            if (typeOfGear.equals(" ")){ typeOfGear="";}
            //float minPrice = Float.parseFloat(minPrice_1);
            //float maxPrice = Float.parseFloat(maxPrice_2);
            
            
            //String calistir = carBrand+carName+minPrice+maxPrice;     
            String query = "Execute [dbo].[sp_SearchCarApplication] '"+carBrand+"','"+carName+"','"+minPrice_1+"','"+maxPrice_2+"','"+typeOfFuel+"','"+typeOfGear+"'";
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            String connectionUrl = "jdbc:sqlserver://MBS;databaseName=searchapplication;integratedSecurity=true;trustServerCertificate=true;"; 
            Connection connection = DriverManager.getConnection(connectionUrl);
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(query);
            String carMarka,carModel ,carYakitTuru ,carVitesTuru,carFiyat ;
            
            
            
            while(resultSet.next()){
                carMarka = resultSet.getString(1);
                carModel  = resultSet.getString(2);
                carYakitTuru = resultSet.getString(3);
                carVitesTuru = resultSet.getString(4);
                carFiyat  = resultSet.getString(5);
//               int carFiyatint=Integer.parseInt(carFiyat);
//               var ab =(Object)new Cars(carMarka,carModel,carYakitTuru,carVitesTuru,carFiyatint);
//                System.err.println(carMarka);
//                System.err.println(carModel);
//                System.err.println(carYakitTuru);
//                System.err.println(carVitesTuru);
//                System.err.println(carFiyat);
//                System.out.println(ab);
            model.addRow(new Object[] {carMarka,carModel,carYakitTuru,carVitesTuru,carFiyat});
            }
            
                
            
        }
            catch(Exception e){
                    System.err.println(e);
       

//        } catch (Exception ex) {
//            Logger.getLogger(SearchApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        JOptionPane.showMessageDialog(null,"For example you can enter a price between two number." + "\n" + "500.000-900.000" );
        JOptionPane.showMessageDialog(null,"You can search for your car by filling in the properties you are looking for.");    }//GEN-LAST:event_btnHelpActionPerformed
 

    private void comboboxFuelTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxFuelTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxFuelTypeActionPerformed

    private void txtMaxPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxPriceActionPerformed

    private void txtMinPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinPriceActionPerformed


        
    }//GEN-LAST:event_txtMinPriceActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void comboboxGearTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxGearTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxGearTypeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddButton addButton = new AddButton();
        addButton.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtMinPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinPriceMouseClicked
        txtMinPrice.setText("");
           
    }//GEN-LAST:event_txtMinPriceMouseClicked

    private void txtMaxPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaxPriceMouseClicked
        txtMaxPrice.setText("");
    }//GEN-LAST:event_txtMaxPriceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        String name= JOptionPane.showInputDialog("What is your name");
//    	String lastName= JOptionPane.showInputDialog("What is your Last Name");   	
//    	JOptionPane.showMessageDialog(null, "Welcome to the search application for the cars " + name + lastName);
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>      
        /* Create and display the form */
        
           MyScreen myScreen = new MyScreen(); 
           myScreen.setVisible(true);
        
         try { 
            for(int i =0 ; i<= 100 ; i++){
                Thread.sleep(40);
                myScreen.lblLoadingValue.setText(i +"%");
                
                if(i== 10){
                    myScreen.lblInformation.setText("Turning Modules...");                   
                }
                if(i== 30){
                    myScreen.lblInformation.setText("Loading Modules...");                   
                }
                if(i== 50){
                    myScreen.lblInformation.setText("Connection to Database...");                   
                }
                if(i== 70){
                    myScreen.lblInformation.setText("Connection Successful...");                   
                }
                if(i== 90){
                    myScreen.lblInformation.setText("Launching...");                   
                }
                myScreen.LoadingBar.setValue(i);
            } 
            myScreen.setVisible(false);
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SearchApplication().setVisible(true);
            }
        });
    
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboboxFuelType;
    private javax.swing.JComboBox<String> comboboxGearType;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCars;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTypeOfFuel;
    private javax.swing.JLabel lblTypeOfGear;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtMaxPrice;
    private javax.swing.JTextField txtMinPrice;
    private javax.swing.JTextField txtModel;
    // End of variables declaration//GEN-END:variables
}
